# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.RemoveField(
            model_name='query',
            name='city',
        ),
        migrations.AddField(
            model_name='query',
            name='location_x',
            field=models.FloatField(default=45.4754418),
        ),
        migrations.AddField(
            model_name='query',
            name='location_y',
            field=models.FloatField(default=-73.5863705),
        ),
    ]
